OliverBooth/Controllers/Blog/RssController.cs
using System.Xml.Serialization;
using Microsoft.AspNetCore.Mvc;
using OliverBooth.Common.Data.Blog;
using OliverBooth.Common.Services;
using OliverBooth.Data.Blog.Rss;

namespace OliverBooth.Controllers.Blog;

[ApiController]
[Route("blog/feed")]
public class RssController : Controller
{
    private readonly IBlogPostService _blogPostService;

    /// <summary>
    ///     Initializes a new instance of the <see cref="RssController" /> class.
    /// </summary>
    /// <param name="blogPostService">The <see cref="IBlogPostService" />.</param>
    public RssController(IBlogPostService blogPostService)
    {
        _blogPostService = blogPostService;
    }

    [HttpGet]
    [Produces("application/xml")]
    public IActionResult OnGet()
    {
        Response.ContentType = "application/xml";

        var baseUrl = $"https://{Request.Host}/blog";
        var blogItems = new List<BlogItem>();

        foreach (IBlogPost post in _blogPostService.GetAllBlogPosts())
        {
            var url = $"{baseUrl}/{post.Published:yyyy/MM/dd}/{post.Slug}";
            string excerpt = _blogPostService.RenderPost(post);
            var description = $"{excerpt}<p><a href=\"{url}\">Read more...</a></p>";

            var item = new BlogItem
            {
                Title = post.Title,
                Link = url,
                Comments = $"{url}#disqus_thread",
                Creator = post.Author.DisplayName,
                PubDate = post.Published.ToString("R"),
                Guid = post.WordPressId.HasValue ? $"{baseUrl}?p={post.WordPressId.Value}" : $"{baseUrl}?pid={post.Id}",
                Description = description
            };
            blogItems.Add(item);
        }

        var rss = new BlogRoot
        {
            Channel = new BlogChannel
            {
                AtomLink = new AtomLink
                {
                    Href = $"{baseUrl}/feed/",
                },
                Description = $"{baseUrl}/",
                LastBuildDate = DateTimeOffset.UtcNow.ToString("R"),
                Link = $"{baseUrl}/",
                Title = "Oliver Booth",
                Generator = $"{baseUrl}/",
                Items = blogItems
            }
        };

        var serializer = new XmlSerializer(typeof(BlogRoot));
        var xmlNamespaces = new XmlSerializerNamespaces();
        xmlNamespaces.Add("content", "http://purl.org/rss/1.0/modules/content/");
        xmlNamespaces.Add("wfw", "http://wellformedweb.org/CommentAPI/");
        xmlNamespaces.Add("dc", "http://purl.org/dc/elements/1.1/");
        xmlNamespaces.Add("atom", "http://www.w3.org/2005/Atom");
        xmlNamespaces.Add("sy", "http://purl.org/rss/1.0/modules/syndication/");
        xmlNamespaces.Add("slash", "http://purl.org/rss/1.0/modules/slash/");

        using var writer = new StreamWriter(Response.BodyWriter.AsStream());
        serializer.Serialize(writer, rss, xmlNamespaces);

        return Ok();
    }
}

OliverBooth/Pages/Blog/Archive.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OliverBooth.Pages.Blog;

public class Archive : PageModel
{
    public void OnGet()
    {
        
    }
}

OliverBooth/Pages/Blog/Article.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Primitives;
using OliverBooth.Common.Data.Blog;
using OliverBooth.Common.Services;
using BC = BCrypt.Net.BCrypt;

namespace OliverBooth.Pages.Blog;

/// <summary>
///     Represents the page model for the <c>Article</c> page.
/// </summary>
[Area("blog")]
public class Article : PageModel
{
    private readonly IBlogPostService _blogPostService;

    /// <summary>
    ///     Initializes a new instance of the <see cref="Article" /> class.
    /// </summary>
    /// <param name="blogPostService">The <see cref="IBlogPostService" />.</param>
    public Article(IBlogPostService blogPostService)
    {
        _blogPostService = blogPostService;
    }

    /*
    /// <summary>
    ///     Gets a value indicating whether the post is a legacy WordPress post.
    /// </summary>
    /// <value>
    ///     <see langword="true" /> if the post is a legacy WordPress post; otherwise, <see langword="false" />.
    /// </value>
    public bool IsWordPressLegacyPost => Post.WordPressId.HasValue;
    */

    /// <summary>
    ///     Gets the requested blog post.
    /// </summary>
    /// <value>The requested blog post.</value>
    public IBlogPost Post { get; private set; } = null!;

    /// <summary>
    ///     Gets a value indicating whether to show the password prompt.
    /// </summary>
    /// <value>
    ///     <see langword="true" /> if the password prompt should be shown; otherwise, <see langword="false" />.
    /// </value>
    public bool ShowPasswordPrompt { get; private set; }

    public IActionResult OnGet(int year, int month, int day, string slug)
    {
        var date = new DateOnly(year, month, day);
        if (!_blogPostService.TryGetPost(date, slug, out IBlogPost? post))
        {
            Response.StatusCode = 404;
            return NotFound();
        }

        if (!string.IsNullOrWhiteSpace(post.Password))
        {
            ShowPasswordPrompt = true;
        }

        if (post.IsRedirect)
        {
            return Redirect(post.RedirectUrl!.ToString());
        }

        Post = post;
        return Page();
    }

    public IActionResult OnPost([FromRoute] int year,
        [FromRoute] int month,
        [FromRoute] int day,
        [FromRoute] string slug)
    {
        var date = new DateOnly(year, month, day);
        if (!_blogPostService.TryGetPost(date, slug, out IBlogPost? post))
        {
            return NotFound();
        }

        ShowPasswordPrompt = true;

        if (Request.Form.TryGetValue("password", out StringValues password) && BC.Verify(password, post.Password))
        {
            ShowPasswordPrompt = false;
        }

        if (post.IsRedirect)
        {
            return Redirect(post.RedirectUrl!.ToString());
        }

        Post = post;
        return Page();
    }
}

OliverBooth/Pages/Blog/Index.cshtml.cs
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OliverBooth.Common.Data.Blog;
using OliverBooth.Common.Services;

namespace OliverBooth.Pages.Blog;

[Area("blog")]
public class Index : PageModel
{
    private readonly IBlogPostService _blogPostService;

    public Index(IBlogPostService blogPostService)
    {
        _blogPostService = blogPostService;
    }

    public string[] Tag { get; private set; } = [];

    public IActionResult OnGet([FromQuery(Name = "pid")] Guid? postId = null,
        [FromQuery(Name = "p")] int? wpPostId = null,
        [FromQuery(Name = "tag")] string? tag = null)
    {
        Tag = tag?.Split('+') ?? [];

        if (postId.HasValue == wpPostId.HasValue)
        {
            return Page();
        }

        return postId.HasValue ? HandleNewRoute(postId.Value) : HandleWordPressRoute(wpPostId!.Value);
    }

    private IActionResult HandleNewRoute(Guid postId)
    {
        return _blogPostService.TryGetPost(postId, out IBlogPost? post) ? RedirectToPost(post) : NotFound();
    }

    private IActionResult HandleWordPressRoute(int wpPostId)
    {
        return _blogPostService.TryGetPost(wpPostId, out IBlogPost? post) ? RedirectToPost(post) : NotFound();
    }

    private RedirectResult RedirectToPost(IBlogPost post)
    {
        var route = new
        {
            year = post.Published.ToString("yyyy"),
            month = post.Published.ToString("MM"),
            day = post.Published.ToString("dd"),
            slug = post.Slug
        };
        return Redirect(Url.Page("/Blog/Article", route)!);
    }
}

OliverBooth/Pages/Blog/List.cshtml.cs
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OliverBooth.Pages.Blog;

/// <summary>
///     Represents a class which defines the model for the <c>/blog/page/#</c> route.
/// </summary>
public class List : PageModel
{
    /// <summary>
    ///     Gets the requested page number.
    /// </summary>
    /// <value>The requested page number.</value>
    public int PageNumber { get; private set; }

    public string[] Tag { get; private set; } = [];

    /// <summary>
    ///     Handles the incoming GET request to the page.
    /// </summary>
    /// <param name="page">The requested page number, starting from 1.</param>
    /// <param name="tag">The tag by which to filter results.</param>
    /// <returns></returns>
    public IActionResult OnGet([FromRoute(Name = "pageNumber")] int page = 1, [FromQuery(Name = "tag")] string? tag = null)
    {
        if (page < 2)
        {
            return RedirectToPage("Index");
        }

        PageNumber = page;
        Tag = tag?.Split('+') ?? [];
        return Page();
    }
}

OliverBooth/Pages/Blog/Posts.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OliverBooth.Pages.Blog;

public class Posts : PageModel
{
    /// <summary>
    ///     Gets the requested page number.
    /// </summary>
    /// <value>The requested page number.</value>
    public int PageNumber { get; private set; }

    public IActionResult OnGet([FromRoute(Name = "pageNumber")] int page = 1)
    {
        if (page < 1)
        {
            return RedirectToPage("Posts");
        }

        PageNumber = page;
        return Page();
    }
}

OliverBooth/Pages/Blog/RawArticle.cshtml.cs
using Cysharp.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OliverBooth.Common.Data.Blog;
using OliverBooth.Common.Services;

namespace OliverBooth.Pages.Blog;

/// <summary>
///     Represents the page model for the <c>RawArticle</c> page.
/// </summary>
[Area("blog")]
public class RawArticle : PageModel
{
    private readonly IBlogPostService _blogPostService;

    /// <summary>
    ///     Initializes a new instance of the <see cref="RawArticle" /> class.
    /// </summary>
    /// <param name="blogPostService">The <see cref="IBlogPostService" />.</param>
    public RawArticle(IBlogPostService blogPostService)
    {
        _blogPostService = blogPostService;
    }

    public IActionResult OnGet(int year, int month, int day, string slug)
    {
        var date = new DateOnly(year, month, day);
        if (!_blogPostService.TryGetPost(date, slug, out IBlogPost? post))
        {
            return NotFound();
        }

        Response.Headers.Add("Content-Type", "text/plain; charset=utf-8");

        using Utf8ValueStringBuilder builder = ZString.CreateUtf8StringBuilder();
        builder.AppendLine("# " + post.Title);
        builder.AppendLine($"Author: {post.Author.DisplayName}");

        builder.AppendLine($"Published: {post.Published:R}");
        if (post.Updated.HasValue)
            builder.AppendLine($"Updated: {post.Updated:R}");

        builder.AppendLine();
        builder.AppendLine(post.Body);
        return Content(builder.ToString());
    }
}

OliverBooth/Pages/Tutorials/Article.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OliverBooth.Common.Data.Web;
using OliverBooth.Common.Services;

namespace OliverBooth.Pages.Tutorials;

/// <summary>
///     Represents the page model for the <c>Article</c> page.
/// </summary>
public class Article : PageModel
{
    private readonly ITutorialService _tutorialService;

    /// <summary>
    ///     Initializes a new instance of the <see cref="Article" /> class.
    /// </summary>
    /// <param name="tutorialService">The <see cref="ITutorialService" />.</param>
    public Article(ITutorialService tutorialService)
    {
        _tutorialService = tutorialService;
    }

    /// <summary>
    ///     Gets the requested article.
    /// </summary>
    /// <value>The requested article.</value>
    public ITutorialArticle CurrentArticle { get; private set; } = null!;

    public IActionResult OnGet(string slug)
    {
        if (!_tutorialService.TryGetArticle(slug, out ITutorialArticle? article))
        {
            Response.StatusCode = 404;
            return NotFound();
        }

        CurrentArticle = article;
        return Page();
    }
}

OliverBooth/Pages/Blog/Archive.cshtml
@page
@using OliverBooth.Common.Data
@using OliverBooth.Common.Data.Blog
@using OliverBooth.Common.Services
@model OliverBooth.Pages.Blog.Archive
@inject IBlogPostService BlogPostService

@{
    ViewData["Page"] = "Archive";
}

<header class="page-header">
    <h1>
        Archive
        <a asp-controller="Rss" asp-action="OnGet" title="RSS" aria-label="RSS">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" height="23">
                <path d="M4 11a9 9 0 0 1 9 9"></path>
                <path d="M4 4a16 16 0 0 1 16 16"></path>
                <circle cx="5" cy="19" r="1"></circle>
            </svg>
        </a>
    </h1>
</header>

@{
    IEnumerable<IBlogPost> posts = BlogPostService.GetAllBlogPosts().Where(p => p.Visibility == Visibility.Published);

    foreach (IGrouping<int, IBlogPost> yearGroup in posts.GroupBy(p => p.Published.Year))
    {
        <div class="archive-year">
            <h2 class="archive-year-header">
                @yearGroup.Key
                <sup class="archive-count">&nbsp;&nbsp;@yearGroup.Count()</sup>
            </h2>

            @foreach (IGrouping<int, IBlogPost> monthGroup in yearGroup.GroupBy(p => p.Published.Month))
            {
                <div class="archive-month">
                    <h3 class="archive-month-header">
                        @(new DateTime(yearGroup.Key, monthGroup.Key, 1).ToString("MMMM"))
                        <sup class="archive-count">&nbsp;&nbsp;@monthGroup.Count()</sup>
                    </h3>

                    <div class="archive-posts">
                        @foreach (IBlogPost post in monthGroup)
                        {
                            IBlogAuthor author = post.Author;
                            DateTimeOffset published = post.Published;
                            int wordCount = post.Body.Split().Length;

                            <div class="archive-entry">
                                <h3 class="archive-entry-title entry-hint-parent">
                                    @post.Title
                                </h3>
                                <div class="archive-meta">
                                    <span title="@(published.ToString("s"))">@published.ToString("D")</span>
                                    &nbsp;·
                                    @Math.Max(1, wordCount / 275) min
                                    ·
                                    @wordCount words
                                    ·
                                    @author.DisplayName
                                </div>

                                <a class="entry-link" aria-label="post link to @post.Title"
                                   asp-page="/Blog/Article"
                                   asp-route-year="@published.Year"
                                   asp-route-month="@published.Month.ToString("00")"
                                   asp-route-day="@published.Day.ToString("00")"
                                   asp-route-slug="@post.Slug">
                                </a>
                            </div>
                        }
                    </div>
                </div>
            }
        </div>
    }
}

OliverBooth/Pages/Blog/Article.cshtml
@page "/blog/{year:int}/{month:int}/{day:int}/{slug}"
@using Humanizer
@using Markdig
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using OliverBooth.Common.Data
@using OliverBooth.Common.Data.Blog
@using OliverBooth.Common.Services
@inject IBlogPostService BlogPostService
@inject MarkdownPipeline MarkdownPipeline
@model Article

@if (Model.ShowPasswordPrompt)
{
    <div class="callout" data-callout="danger">
        This post is private and can only be viewed by those with the password.
    </div>

    <form method="post">
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password" name="password" required>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    return;
}

@if (Model.Post is not { } post)
{
    return;
}

@{
    ViewData["Page"] = "Blog";
    ViewData["Post"] = post;
    ViewData["Title"] = post.Title;
    IBlogAuthor author = post.Author;
    DateTimeOffset published = post.Published;
}

<article class="post-single">
    <header class="post-header">
        <div class="breadcrumbs">
            <a asp-page="/Index">Home</a>
            &nbsp;»&nbsp;
            <a asp-page="/Blog/Posts">Posts</a>
            &nbsp;»&nbsp;
            <a asp-page="/Blog/Article"
               asp-route-year="@published.Year"
               asp-route-month="@published.Month.ToString("00")"
               asp-route-day="@published.Day.ToString("00")"
               asp-route-slug="@post.Slug">
                @post.Title
            </a>
        </div>
        <h1 class="post-title entry-hint-parent">@post.Title</h1>
        <div class="post-meta">
            <span title="@(published.ToString("s"))">@published.ToString("D")</span>
            &nbsp;·
            @Math.Max(1, post.Body.Split().Length / 275) min
            ·
            @author.DisplayName
        </div>
    </header>

    @switch (post.Visibility)
    {
        case Visibility.Private:
            <div class="callout" data-callout="danger">
                This post is private and can only be viewed by those with the password.
            </div>
            break;

        case Visibility.Unlisted:
            <div class="callout" data-callout="warning">
                This post is unlisted and can only be viewed by those with the link.
            </div>
            break;
    }

    <div class="post-content">
        @Html.Raw(BlogPostService.RenderPost(post))
    </div>

    <footer class="post-footer">
        <ul class="post-tags">
            @foreach (string tag in post.Tags)
            {
                <li>
                    <a asp-page="/Blog/Index" asp-route-tag="@tag">@tag.Replace('-', ' ')</a>
                </li>
            }
        </ul>
        <nav class="paginav">
            @if (BlogPostService.GetPreviousPost(post) is { } previousPost)
            {
                <a class="prev" asp-page="Article"
                   asp-route-year="@previousPost.Published.Year.ToString("0000")"
                   asp-route-month="@previousPost.Published.Month.ToString("00")"
                   asp-route-day="@previousPost.Published.Day.ToString("00")"
                   asp-route-slug="@previousPost.Slug">
                    <span class="title">« Prev</span>
                    <br>
                    <span>@previousPost.Title</span>
                </a>
            }
            @if (BlogPostService.GetNextPost(post) is { } nextPost)
            {
                <a class="next" asp-page="Article"
                   asp-route-year="@nextPost.Published.Year.ToString("0000")"
                   asp-route-month="@nextPost.Published.Month.ToString("00")"
                   asp-route-day="@nextPost.Published.Day.ToString("00")"
                   asp-route-slug="@nextPost.Slug">
                    <span class="title">Next »</span>
                    <br>
                    <span>@nextPost.Title</span>
                </a>
            }
        </nav>
    </footer>
</article>


@if (post.EnableComments)
{
    <div class="giscus"></div>
    @section Scripts
    {
        <script src="https://giscus.app/client.js"
                data-repo="oliverbooth/oliverbooth.dev"
                data-repo-id="MDEwOlJlcG9zaXRvcnkyNDUxODEyNDI="
                data-category="Comments"
                data-category-id="DIC_kwDODp0rOs4Ce_Nj"
                data-mapping="pathname"
                data-strict="0"
                data-reactions-enabled="1"
                data-emit-metadata="0"
                data-input-position="bottom"
                data-theme="preferred_color_scheme"
                data-lang="en"
                crossorigin="anonymous"
                async>
    </script>
    }
}
else
{
    <p class="no-comment">Comments are not enabled for this post.</p>
}

@{
    int commentCount = BlogPostService.GetLegacyCommentCount(post);
    if (commentCount > 0)
    {
        <hr>

        var nestLevelMap = new Dictionary<ILegacyComment, int>();
        IReadOnlyList<ILegacyComment> legacyComments = BlogPostService.GetLegacyComments(post);
        var commentStack = new Stack<ILegacyComment>(legacyComments.OrderByDescending(c => c.CreatedAt));
        <p class="legacy-comment-counter">
            <strong>@("legacy comment".ToQuantity(commentCount))</strong>
        </p>
        <p class="legacy-comment-subtitle">
            <sub>Legacy comments are comments that were posted using a commenting system that I no longer use. This exists for posterity.</sub>
        </p>

        while (commentStack.Count > 0)
        {
            ILegacyComment comment = commentStack.Pop();
            foreach (ILegacyComment reply in BlogPostService.GetLegacyReplies(comment).OrderByDescending(c => c.CreatedAt))
            {
                if (nestLevelMap.TryGetValue(comment, out int currentLevel))
                {
                    nestLevelMap[reply] = currentLevel + 1;
                }
                else
                {
                    nestLevelMap[reply] = 1;
                }

                commentStack.Push(reply);
            }

            int padding = 0;
            if (nestLevelMap.TryGetValue(comment, out int nestLevel))
            {
                padding = 50 * nestLevel;
            }

            <div class="legacy-comment" style="margin-left: @(padding)px;">
                <img class="blog-author-icon" src="@comment.GetAvatarUrl()" alt="@comment.Author">
                @comment.Author ·

                <abbr class="text-muted" title="@comment.CreatedAt.ToString("dddd, d MMMM yyyy HH:mm")">
                    @comment.CreatedAt.Humanize()
                </abbr>

                <div class="comment">@Html.Raw(Markdown.ToHtml(comment.Body, MarkdownPipeline))</div>
            </div>
        }
    }
}

OliverBooth/Pages/Blog/Index.cshtml
@page
@using OliverBooth.Common.Data
@using OliverBooth.Common.Services
@model Index
@inject IBlogPostService BlogPostService

@{
    ViewData["Title"] = "Blog";
    ViewData["Page"] = "Blog";
}

@await Html.PartialAsync("Shared/Partials/_HomeInfoEntry")
@await Html.PartialAsync("Shared/Partials/_BlogEntries", new ViewDataDictionary(ViewData)
{
    ["CurrentPage"] = 0,
    ["Tags"] = Model.Tag
})

@{
    int pageCount = BlogPostService.GetPageCount(tags: Model.Tag, visibility: Visibility.Published);
    if (pageCount > 1)
    {
        <footer class="page-footer">
            <nav class="pagination">
                <a class="next" asp-page="/Blog/List" asp-route-pageNumber="2">Next&nbsp;2/@pageCount&nbsp;»</a>
            </nav>
        </footer>
    }
}

OliverBooth/Pages/Blog/List.cshtml
@page "/blog/page/{pageNumber:int}"
@model List
@using OliverBooth.Common.Data
@using OliverBooth.Common.Data.Blog
@using OliverBooth.Common.Services
@inject IBlogPostService BlogPostService

@{
    ViewData["Title"] = "Blog";
    ViewData["Page"] = "Blog";
    int pageCount = BlogPostService.GetPageCount(tags: Model.Tag, visibility: Visibility.Published);
    int previousPage = Model.PageNumber - 1;
    int nextPage = Model.PageNumber + 1;
}

@await Html.PartialAsync("Shared/Partials/_HomeInfoEntry")
@await Html.PartialAsync("Shared/Partials/_BlogEntries", new ViewDataDictionary(ViewData)
{
    ["CurrentPage"] = previousPage // -1 for zero based
})

@{
<footer class="page-footer">
    <nav class="pagination">
        <a class="previous" asp-page="/Blog/List" asp-route-pageNumber="@previousPage">«&nbsp;Previous&nbsp;@previousPage/@pageCount</a>
        @if (Model.PageNumber < pageCount)
        {
            <a class="next" asp-page="/Blog/List" asp-route-pageNumber="@nextPage">Next&nbsp;@nextPage/@pageCount&nbsp;»</a>
        }
    </nav>
</footer>
}

OliverBooth/Pages/Blog/Posts.cshtml
@page "/blog/posts/{**pageNumber:int}"
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using OliverBooth.Common.Data
@using OliverBooth.Common.Services
@model OliverBooth.Pages.Blog.Posts
@inject IBlogPostService BlogPostService

<header class="page-header">
    <div class="breadcrumbs">
        <a asp-page="/Index">Home</a>
    </div>

    <h1>
        Posts
        <a asp-controller="Rss" asp-action="OnGet" title="RSS" aria-label="RSS">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" height="23">
                <path d="M4 11a9 9 0 0 1 9 9"></path>
                <path d="M4 4a16 16 0 0 1 16 16"></path>
                <circle cx="5" cy="19" r="1"></circle>
            </svg>
        </a>
    </h1>
</header>

@await Html.PartialAsync("Shared/Partials/_BlogEntries", new ViewDataDictionary(ViewData)
{
    ["CurrentPage"] = 0
})

@{
    int pageCount = BlogPostService.GetPageCount(visibility: Visibility.Published);
    int previousPage = Model.PageNumber - 1;
    int nextPage = Model.PageNumber + 1;

    if (pageCount > 1)
    {
        <footer class="page-footer">
            <nav class="pagination">
                @if (Model.PageNumber > 1)
                {
                    <a class="previous" asp-page="/Blog/List" asp-route-pageNumber="@previousPage">«&nbsp;Previous&nbsp;@previousPage/@pageCount</a>
                }
                else if (Model.PageNumber < pageCount)
                {
                    <a class="next" asp-page="/Blog/List" asp-route-pageNumber="@nextPage">Next&nbsp;@nextPage/@pageCount&nbsp;»</a>
                }
            </nav>
        </footer>
    }
}

OliverBooth/Pages/Blog/RawArticle.cshtml
@page "/blog/{year:int}/{month:int}/{day:int}/{slug}/raw"
@model RawArticle